name: Playwright Baseline

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read

jobs:
  generate-baseline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fe
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.18.0

    - name: Cache dependencies
      uses: actions/cache@v4
      id: yarn-cache
      with:
        path: fe/node_modules
        key: yarn-${{ hashFiles('fe/yarn.lock') }}

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('fe/yarn.lock') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install Playwright browsers and dependencies
      run: |
        if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != "true" ]; then
          npx playwright install --with-deps > /dev/null # --quiet
        else
          npx playwright install-deps > /dev/null # --quiet
        fi

    - name: Generate baseline screenshots
      run: npx playwright test --update-snapshots

    - name: Upload baseline snapshots as artifact
      uses: actions/upload-artifact@v4
      with:
        name: playwright-baseline-snapshots
        path: fe/.tests/snaps/
        retention-days: 60
        overwrite: true

    - name: Add summary
      if: always()
      # add artifact download link to the summary
      run: |
        if [ $? -ne 0 ]; then
          echo "### ❌ Playwright Baseline Generation Failed" >> $GITHUB_STEP_SUMMARY
          echo "Check the logs for details." >> $GITHUB_STEP_SUMMARY
        else
          echo "### ✅ Baseline snapshots have been updated and stored as an artifact" >> $GITHUB_STEP_SUMMARY
          echo "Link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
