name: Playwright Baseline

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  generate-baseline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.18.0

    - name: Cache yarn dependencies
      uses: actions/cache@v4
      id: yarn-cache
      with:
        path: fe/node_modules
        key: yarn-${{ hashFiles('fe/yarn.lock') }}

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      working-directory: ./fe
      run: yarn install --frozen-lockfile

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('fe/yarn.lock') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install Playwright browsers and dependencies
      working-directory: ./fe
      run: |
        if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != "true" ]; then
          echo "Cache miss - installing browsers and dependencies"
          npx playwright install --with-deps
        else
          echo "Cache hit - installing only system dependencies"
          npx playwright install-deps
        fi

    - name: Generate baseline screenshots
      working-directory: ./fe
      run: npx playwright test --update-snapshots

    - name: Cache baseline screenshots
      uses: actions/cache/save@v4
      with:
        path: fe/.tests/snaps
        key: playwright-baseline-snapshots
